export const GET_TABLE_LIST = "GET_TABLE_LIST";
export const GETTING_TABLE_LIST = "GETTING_TABLE_LIST";
export const CHECK_OUT = "CHECK_OUT";
export const GETTING_ORDER_LIST = "GETTING_ORDER_LIST";
export const GET_ORDER_LIST = "GET_ORDER_LIST";
export const GETTING_PRODUCT = "GETTING_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
