export const GET_TABLE_LIST = "GET_TABLE_LIST";
export const GETTING_TABLE_LIST = "GETTING_TABLE_LIST";
export const INCREASE_FOOD = "INCREASE_FOOD";
export const DECREASE_FOOD = "DECREASE_FOOD";
export const CHECK_OUT = "CHECK_OUT";
